import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { skinMarkup } from '../index.js'
import { startMornyeDesktop } from '../desktop/runtime.js'

export const root = fileURLToPath(new URL('..', import.meta.url))
export function buildDesktop(destination = resolve(root, 'dist/desktop')) {
  mkdirSync(destination, { recursive: true })
  const legacy = readFileSync(resolve(root, 'styles/mornye.css'), 'utf8')
  const variables = legacy.slice(legacy.indexOf('body:not'), legacy.indexOf('/* ---------- real rc.6'))
  const decoration = legacy.slice(legacy.indexOf('.mornye-topbar__brand {'), legacy.indexOf('@media (max-width: 1479px)'))
  const dock = legacy.slice(legacy.indexOf('/* ---------- independent sidebar identity card'), legacy.indexOf('/* ---------- observation terminal masthead'))
  const avatar = 'data:image/png;base64,' + readFileSync(resolve(root, 'assets/mornye-avatar.png')).toString('base64')
  const css = (variables + dock + decoration + readFileSync(resolve(root, 'desktop/overrides.css'), 'utf8')).replaceAll('__MORNYE_AVATAR__', avatar)
  const markup = skinMarkup().replace('SEARCH USER + MORNYE', 'SEARCH LOADED MESSAGES').replace('WEB / CHECKING', 'DESKTOP / LOCAL')
  const client = `// Generated by scripts/build-desktop.mjs; edit desktop/runtime.js and desktop/overrides.css.\nwindow.__ModuleLoader__.load({\n  id: 'dsh-mornye-desktop-skin',\n  factory: () => {\n    ${startMornyeDesktop.toString()}\n    return { apply(ctx) { ctx.effect(() => startMornyeDesktop(${JSON.stringify({ css, markup })}), 'mornye desktop visual skin'); } };\n  }\n});\n`
  writeFileSync(resolve(destination, 'client.js'), client)
  for (const name of ['package.json', 'index.js', 'cordis.patch.yml']) copyFileSync(resolve(root, 'desktop', name), resolve(destination, name))
  return { destination, css, markup, client }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) console.log(buildDesktop().destination)
